### ISSUE TITLE
Release Checklist

### ISSUE THREAD

**Issue by jlahman** [fourkgamedevs/fourk#1]
- [x] Make the app icon
- [x] Add Release tag to the metainfo
- [ ] Make release on github
- [ ] Setup CI
- [ ] Add Copyright info
- [ ] update elementary flatpak runtime to 7
- [ ] V1.0 RELEASED
